### PR TITLE
Dmafd bug fix

### PR DESCRIPTION
**Pull request by yashrajsapra**
Resolved getHostPtr Bug from DMAFDWrapperModule

Type:  Bug fix 

**Checklist**

- [ ] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

### CODE REVIEW

**Comment by mraduldubey** [comment]
Is this pr still relevant @yashrajsapra

**Comment by mraduldubey** [comment]
@yashrajsapra please summarise current status

**Comment by yashrajsapra** [comment]
@mraduldubey This issue is resolved now but we are also planning to add capabilities where anyone can access the buffer based on requirements 
 We will have 3 enums

1. Only Read (fastest)
2. Only Write
3. Read & Write (Slowest)

@venkat0907 Will commit those changes

**Comment by mraduldubey** [comment]
@venkat0907 will do a new PR. Lets create a issue for this.

**Pull request closed without merging**
